### ISSUE TITLE
24w13a not working

### ISSUE THREAD

**Issue by rohanverma2007** [LMokahel/note-block-charged#4]
The note block doesn't play any sound or turn blue in the latest snapshot for some reason.

**Comment by LMokahel** [comment]
> The note block doesn't play any sound or turn blue in the latest snapshot for some reason.

I assume you're talking about version 24w13a, as the title suggests. I just checked both normal lightning strikes and the lightning rod on top getting struck, and both work fine. Are you sure you are using my custom note block and not the Minecraft note block? Did you download the fabric API along with my mod? And would you be able to provide a video of this issue?
